/* ----------------------- */
// Common
/* ----------------------- */

export const SET_ADDRESS = "SET_ADDRESS";
export const NETWORK_SET = "NETWORK_SET";
export const SET_PROVIDER = "SET_PROVIDER";

export const ENABLE_REQUEST = "ENABLE_REQUEST";
export const ENABLE_SUCCESS = "ENABLE_SUCCESS";
export const ENABLE_FAILURE = "ENABLE_FAILURE";

/* ----------------------- */
// Contract
/* ----------------------- */
export const INIT_CONTRACT_REQUEST = "INIT_CONTRACT_REQUEST";
export const INIT_CONTRACT_SUCCESS = "INIT_CONTRACT_SUCCESS";
export const INIT_CONTRACT_FAILURE = "INIT_CONTRACT_FAILURE";

export const CONTRACT_INITIALIZE_REQUEST = "CONTRACT_INITIALIZE_REQUEST";
export const CONTRACT_INITIALIZE_SUCCESS = "CONTRACT_INITIALIZE_SUCCESS";
export const CONTRACT_INITIALIZE_FAILURE = "CONTRACT_INITIALIZE_FAILURE";

export const CONTRACT_INIT_FROM_LIBRARY = "CONTRACT_INIT_FROM_LIBRARY";
